CodingErik/totallyNotTheDarkSide

Api.js
hubbleNewsAPI.js
indextestingjs.html
spaceflightnews.js

made some syncing modifications with dale for the API's

syncing up htmlwith dale

---

assets/css/style.css
index.html

changed labels in nav bar and updated some classes and css.

changes to the navbar

---

Api.js
hubbleNewsAPI.js
index.html
indextestingjs.html

added  hubble Api reponse
added search querys for hubble and space X

Front end search/erik de luna

---

Api.js
index.html

correcting conflict

---

index.html

accepted change in index

---

assets/css/style.css
assets/js/Api.js
index.html

populating image or video of the day

populating image or video of the day

---

assets/css/style.css
assets/js/Api.js
index.html

launch date cards are populating with some styling

---

index.html

rearranged order of divs

---

assets/css/style.css
assets/js/materialize.js
index.html

added reponsive search query and buttons with dale

added reponsive query search and buttons

---

assets/css/style.css
assets/js/hubbleNewsAPI.js
assets/js/spaceflightnews.js
index.html

set up space flight dynamics and hubble news dynamic functionality together with dale

set up space flight dynamics and hubble news dynamic functionality

---

assets/js/Api.js
assets/js/spaceXAPI.js
assets/js/spaceflightnews.js
index.html

buttons for space X working next push set up parameters to pull from API

buttons for space X working next push set up parameters to pull from API

---

assets/js/spaceXAPI.js
assets/js/spaceflightnews.js
index.html

Finish space x query build/erik dale

Finish space x query build/erik dale

---

assets/js/hubbleNewsAPI.js
assets/js/materialize.js
assets/js/spaceXAPI.js
index.html

finished testing on mvp for the project

Space x radio buttons response/erik

---

assets/js/Api.js

adding classes for john to work with

adding classes for john to work with

---

assets/css/style.css
index.html

I'm just here for the new div's

reaching for div update

---

assets/js/hubbleGlossaryAPI.js
assets/js/materialize.js

Erik issue more bugs

---

assets/js/spaceXAPI.js

adding classes for john

---

assets/js/spaceflightnews.js
index.html

"fixed up and down key issue on space flight news. introduced error message in news div"

fixed no search results message

---

assets/css/style.css
index.html

Pushing current changes and updating for styling edits to be made.

John issue css styling

---

assets/js/hubbleGlossaryAPI.js
assets/js/materialize.js
assets/js/spaceXAPI.js

Erik adding target blank

---

assets/js/hubbleGlossaryAPI.js
assets/js/spaceXAPI.js
index.html

Erik issue adding more classes for john

Erik issue adding more classes for john

---

index.html

me and john agreed on this change together, changing button layout

changing button layout ~ me and john agreed on this change together, changing button layout

---

assets/css/style.css

This should apply all the updates except for Space flight News.
Will break for lunch and then finish that one and should be done after that.

John styling branch

---

assets/js/spaceflightnews.js

Dale update sfn

---

assets/js/spaceflightnews.js
index.html

changes form...and removes need for keyup

adding form in place of textarea

---

assets/js/materialize.js
assets/js/spaceflightnews.js

placeholder fixed css removed from SFN

fixed placeholder

---

assets/js/hubbleGlossaryAPI.js

put definition on card via dale suggestion

put definition on card via dale suggestion

---

assets/css/style.css

This should be everything you need on my end for styling the site unrelated to mobile response.

this should be the final commit
